---
- name: configure antora1
  hosts: web_server
  become: yes
  gather_facts: no
    #remote_user: nick
  vars_files:
    - vars/main.yml
  tasks:

  - name: Add the user 'ansible' with a bash shell, appending the group 'wheel'
    ansible.builtin.user:
      name: ansible
      groups: wheel
      append: yes

  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: ansible
      state: present
      key: "{{ lookup('file', '/home/nick/.ssh/id_rsa.pub') }}"

