---
- name: configure antora1
  hosts: web_server
  become: yes
  gather_facts: no
  #remote_user: nick
  roles:
    - ansible-target
  tasks:


# lots more 
# nvm
# /Users/nickhardiman/Documents/tech/product/node/nvm-notes.txt
# https://github.com/nvm-sh/nvm#ansible
# node
# nvm install --lts
# antora
# /Users/nickhardiman/Documents/tech/product/antora/antora-notes.txt
# https://docs.antora.org/antora/latest/install-and-run-quickstart/
# apache
# docroot
# /home/nick/articles-rhel9-build/build/site/
# antora lunr extension 
# antora-search-notes.txt
