---
- name: lay the foundation
  hosts: web_server
  become: yes
  gather_facts: no
  #remote_user: nick
  roles:
    - ansible-target
    - ansible-web-server

- name: build the antora application
  hosts: web_server
  become: no
  gather_facts: no
  # make sure the remote authorized_keys file contains ansible's public key
  remote_user: nick
  roles:
    - ansible-antora-generator


# to do
# antora lunr extension 
# antora-search-notes.txt

