---
- name: build new machine
  hosts: localhost
  #hosts: hypervisor
  become: yes
  gather_facts: no
  roles: 
  - role: libvirt-guest
    # !!!
    ignore_errors: yes

- name: check new machine
  hosts: web_server
  become: no
  gather_facts: no
  tasks:
  - name: Wait for new server to be ready
    ansible.builtin.wait_for_connection:
      timeout: 30

- name: install the foundation
  hosts: web_server
  become: yes
  vars:
    ansible_become_password: Password;1
  gather_facts: no
  roles:
    - ansible-target
    - ansible-web-server

- name: build the antora application
  hosts: web_server
  become: no
  gather_facts: no
  # make sure the remote authorized_keys file contains ansible's public key
  remote_user: "{{ user }}"
  roles:
    - ansible-antora-generator


# to do
# antora lunr extension 
# antora-search-notes.txt

    
    
    
