---
- name: build new machine
  hosts: localhost
  #hosts: hypervisor
  become: yes
  gather_facts: no
  roles: 
  - role: libvirt-guest

- name: check new machine
  hosts: web_server
  become: no
  gather_facts: no
  tasks:
  - name: Wait for new server to be ready
    ansible.builtin.wait_for_connection:
      timeout: 30

