# I want antora installed using my account, not ansible's.
#
- name: build the antora application
  hosts: web_server
  # a few tasks do require elevated privileges
  become: no
  gather_facts: no
  # make sure the remote authorized_keys file contains ansible's public key
  roles:
    - ansible-antora-generator

# todo
# antora lunr extension 
# antora-search-notes.txt
