---
- name: build antora1 machine
  hosts: hypervisor
  become: yes
  gather_facts: no
  roles: 
  - role: libvirt-guest
    vars:
      host: antora1
      # list in https://hardiman.consulting/rhel/9/set-up/host1-libvirt-network.html
      if1_mac: "52:54:00:00:00:17"

- name: install the foundation
  hosts: web_server
  become: yes
  gather_facts: no
  roles:
    - ansible-target
    - ansible-web-server

- name: build the antora application
  hosts: web_server
  become: no
  gather_facts: no
  # make sure the remote authorized_keys file contains ansible's public key
  remote_user: "{{ user }}"
  roles:
    - ansible-antora-generator


# to do
# antora lunr extension 
# antora-search-notes.txt

    
    
    