---
- name: install node
  hosts: web_server
  become: yes
  gather_facts: no
  vars:
    node_installed: no
  tasks:

    - name: is node already installed?
      ansible.builtin.shell: 
        cmd: bash -i -l -c 'node -v'
        #cmd: bash -i -l -c 'source ~/.bashrc && node -v'
      register: r_node
      ignore_errors: yes

    - set_fact:
        node_installed: yes
      when: r_node.rc == 0
    
    - debug:
        var: node_installed

    - name: Install node
      ansible.builtin.shell: >
        bash -i -l -c 'nvm install --lts'
      args:
        chdir: "$HOME"
        creates: "$HOME/.nvm/versions/node"
      when: not node_installed
      changed_when: yes

