#  ansible-playbook  --ask-become-pass  delete.yml
# or
#  ansible-playbook  --become-password-file=~/my-pass --extra-var='host=another-host' delete.yml
---
- name: remove virt domain
  hosts: localhost
  become: yes
  gather_facts: no
  tasks:

  - name: pull the plug
    command:
      cmd: "virsh destroy {{ host }}"

  - name: delete everything
    command:
      cmd: "virsh undefine --nvram --remove-all-storage {{ host }}"


